# App-specific tweaks
source = ./apps/1password.conf
source = ./apps/bitwarden.conf
source = ./apps/browser.conf
source = ./apps/hyprshot.conf
source = ./apps/jetbrains.conf
source = ./apps/localsend.conf
source = ./apps/pip.conf
source = ./apps/qemu.conf
source = ./apps/retroarch.conf
source = ./apps/steam.conf
source = ./apps/geforce.conf
source = ./apps/moonlight.conf
source = ./apps/system.conf
source = ./apps/telegram.conf
source = ./apps/terminals.conf
source = ./apps/walker.conf
source = ./apps/webcam-overlay.conf
