# Menus
bindd = SUPER, SPACE, Launch apps, exec, launch-walker
bindd = SUPER CTRL, E, Emoji picker, exec, launch-walker -m symbols
bindd = SUPER CTRL, C, Capture menu, exec, menu-open capture
bindd = SUPER CTRL, O, Toggle menu, exec, menu-open toggle
bindd = SUPER ALT, SPACE, Menu, exec, menu-open
bindd = SUPER, ESCAPE, System menu, exec, menu-open system
bindld = , XF86PowerOff, Power menu, exec, menu-open system
bindd = SUPER, K, Show key bindings, exec, menu-keybindings
bindd = , XF86Calculator, Calculator, exec, gnome-calculator

# Aesthetics
bindd = SUPER SHIFT, SPACE, Toggle top bar, exec, toggle-waybar
bindd = SUPER, BACKSPACE, Toggle window transparency, exec, hyprctl dispatch setprop "address:$(hyprctl activewindow -j | jq -r '.address')" opaque toggle
bindd = SUPER SHIFT, BACKSPACE, Toggle window gaps, exec, hyprland-window-gaps-toggle
bindd = SUPER CTRL, BACKSPACE, Toggle single-window square aspect, exec, hyprland-window-single-square-aspect-toggle

# Notifications
bindd = SUPER, COMMA, Dismiss last notification, exec, makoctl dismiss
bindd = SUPER SHIFT, COMMA, Dismiss all notifications, exec, makoctl dismiss --all
bindd = SUPER CTRL, COMMA, Toggle silencing notifications, exec, toggle-notification-silencing
bindd = SUPER ALT, COMMA, Invoke last notification, exec, makoctl invoke
bindd = SUPER SHIFT ALT, COMMA, Restore last notification, exec, makoctl restore

# Toggles
bindd = SUPER CTRL, I, Toggle locking on idle, exec, toggle-idle
bindd = SUPER CTRL, N, Toggle nightlight, exec, toggle-nightlight

# Captures
bindd = , PRINT, Screenshot, exec, cmd-screenshot
bindd = SUPER, PRINT, Color picker, exec, pkill hyprpicker || hyprpicker -a

# Waybar-less information
bindd = SUPER CTRL ALT, T, Show time, exec, notify-send "    $(date +"%A %H:%M  —  %d %B W%V %Y")"
bindd = SUPER CTRL ALT, B, Show battery remaining, exec, notify-send "$(battery-status)"

# Control panels
bindd = SUPER CTRL, A, Audio controls, exec, launch-audio
bindd = SUPER CTRL, B, Bluetooth controls, exec, launch-bluetooth
bindd = SUPER CTRL, W, Wifi controls, exec, launch-wifi
bindd = SUPER CTRL, T, Activity, exec, launch-tui btop

# Dictation
bindd = SUPER CTRL, X, Toggle dictation, exec, voxtype record toggle

# Zoom
bindd = SUPER CTRL, Z, Zoom in, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float + 1')
bindd = SUPER CTRL ALT, Z, Reset zoom, exec, hyprctl keyword cursor:zoom_factor 1

# Lock system
bindd = SUPER SHIFT, L, Lock system, exec, cmd-lock-screen
