# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

source = ./hyprland/apps.conf
source = ./hyprland/autostart.conf
source = ./hyprland/bindings.conf
source = ./hyprland/envs.conf
source = ./hyprland/input.conf
source = ./hyprland/looknfeel.conf
source = ./hyprland/monitors.conf
source = ./hyprland/windows.conf

# Machine local configs

source = ./local/bindings.conf
source = ./local/monitors.conf